___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# Topic Modeling Assessment Project

Welcome to your Topic Modeling Assessment! For this project you will be working with a dataset of over 400,000 quora questions that have no labeled cateogry, and attempting to find 20 cateogries to assign these questions to. The .csv file of these text questions can be found underneath the Topic-Modeling folder.

Remember you can always check the solutions notebook and video lecture for any questions.

#### Task: Import pandas and read in the quora_questions.csv file.

In [23]:
import  pandas as pd

In [24]:
df = pd.read_csv('quora_questions.csv')

In [25]:
df.head()

Question
0  What is the step by step guide to invest in sh...
1  What is the story of Kohinoor (Koh-i-Noor) Dia...
2  How can I increase the speed of my internet co...
3  Why am I mentally very lonely? How can I solve...
4  Which one dissolve in water quikly sugar, salt...

# Preprocessing

#### Task: Use TF-IDF Vectorization to create a vectorized document term matrix. You may want to explore the max_df and min_df parameters.

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [27]:
tfidf = TfidfVectorizer(max_df= 0.77 , min_df= 2 , stop_words= 'english')

In [28]:
dtm = tfidf.fit_transform(df['Question'])

In [29]:
dtm

<404289x38669 sparse matrix of type '<class 'numpy.float64'>'
	with 2002912 stored elements in Compressed Sparse Row format>

# Non-negative Matrix Factorization

#### TASK: Using Scikit-Learn create an instance of NMF with 20 expected components. (Use random_state=42)..

In [30]:
from sklearn.decomposition import NMF

In [31]:
nmf = NMF(n_components= 7 , random_state=42)

In [32]:
nmf.fit(dtm)

NMF(alpha=0.0, beta_loss='frobenius', init=None, l1_ratio=0.0, max_iter=200,
  n_components=7, random_state=42, shuffle=False, solver='cd', tol=0.0001,
  verbose=0)

#### TASK: Print our the top 15 most common words for each of the 20 topics.

In [33]:
nmf.components_

array([[1.03319544e-04, 5.08796629e-02, 4.64506947e-05, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.61359196e-03, 2.56800113e-03, 3.36302425e-05, ...,
        2.99796389e-06, 2.76933593e-03, 2.99796389e-06],
       [3.88559577e-05, 0.00000000e+00, 2.14751999e-06, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [5.75056304e-04, 3.35280511e-03, 0.00000000e+00, ...,
        2.13013802e-06, 0.00000000e+00, 2.13013802e-06],
       [9.21208812e-04, 1.17569707e-02, 0.00000000e+00, ...,
        8.48245973e-06, 0.00000000e+00, 8.48245973e-06],
       [4.64701918e-04, 0.00000000e+00, 0.00000000e+00, ...,
        2.61022893e-05, 0.00000000e+00, 2.61022893e-05]])

In [34]:
for index , topic in enumerate(nmf.components_):
    
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([tfidf.get_feature_names()[i] for i in topic.argsort()[-15:]])
    print()

THE TOP 15 WORDS FOR TOPIC #0
['learning', 'android', 'hollywood', 'app', 'free', 'world', 'site', 'thing', 'engineering', 'friend', 'read', 'website', 'place', 'visit', 'places', 'phone', 'india', 'lose', 'buy', 'laptop', 'time', 'movie', 'ways', '2016', 'weight', 'books', 'book', 'movies', 'way', 'best']

THE TOP 15 WORDS FOR TOPIC #1
['weight', 'facebook', 'good', 'universities', 'grads', 'differ', 'majors', 'recruit', 'looking', 'relationship', 'guy', 'use', 'know', 'person', 'exist', 'new', 'compare', 'look', 'cost', 'really', 'girl', 'love', 'long', 'sex', 'time', 'work', 'feel', 'like', 'mean', 'does']

THE TOP 15 WORDS FOR TOPIC #2
['profile', 'write', 'users', 'writer', 'account', 'instead', 'marked', 'follow', 'think', 'googling', 'search', 'add', 'know', 'don', 'needing', 'post', 'answered', 'use', 'improvement', 'delete', 'easily', 'asked', 'google', 'answer', 'answers', 'ask', 'question', 'questions', 'people', 'quora']

THE TOP 15 WORDS FOR TOPIC #3
['account', 'year', 's

#### TASK: Add a new column to the original quora dataframe that labels each question into one of the 20 topic categories.

In [35]:
dtm.shape

(404289, 38669)

In [36]:
len(df)

404289

In [37]:
topic_result = nmf.transform(dtm)

In [39]:
topic_result.shape

(404289, 7)

In [40]:
topic_result[3]

array([4.58839405e-05, 3.75857443e-04, 2.91968029e-04, 1.83219133e-04,
       1.20411397e-04, 2.61643015e-04, 5.69668894e-05])

In [41]:
topic_result[3].round(2)

array([0., 0., 0., 0., 0., 0., 0.])

In [43]:
topic_result[3].argmax()

1

In [44]:
df.head()

Question
0  What is the step by step guide to invest in sh...
1  What is the story of Kohinoor (Koh-i-Noor) Dia...
2  How can I increase the speed of my internet co...
3  Why am I mentally very lonely? How can I solve...
4  Which one dissolve in water quikly sugar, salt...

In [45]:
df['Topic'] = topic_result.argmax(axis = 1)

In [47]:
df.head(10)

Question  Topic
0  What is the step by step guide to invest in sh...      5
1  What is the story of Kohinoor (Koh-i-Noor) Dia...      4
2  How can I increase the speed of my internet co...      3
3  Why am I mentally very lonely? How can I solve...      1
4  Which one dissolve in water quikly sugar, salt...      1
5  Astrology: I am a Capricorn Sun Cap moon and c...      1
6                                Should I buy tiago?      0
7                     How can I be a good geologist?      6
8                    When do you use シ instead of し?      2
9  Motorola (company): Can I hack my Charter Moto...      0

# Great job!